// Sample data for UNTOUCHABLE dashboard
// This simulates real prediction data that would come from the engine

export const activePredictions = [
  {
    id: "pred_001",
    type: "CRYPTO",
    asset: "BTC",
    prediction: "PUMP",
    confidence: 87,
    timeframe: "24-48 hours",
    targetMove: "+12% to +18%",
    entryPrice: "$67,500",
    targetPrice: "$75,600 - $79,650",
    signals: [
      { name: "whale_accumulation", active: true, strength: 0.92, detail: "3 wallets >$100M bought 2,500 BTC" },
      { name: "social_surge", active: true, strength: 0.88, detail: "Twitter mentions +300%, 85% positive" },
      { name: "exchange_outflow", active: true, strength: 0.85, detail: "8,500 BTC moved from exchanges" },
      { name: "volume_spike", active: true, strength: 0.90, detail: "Trading volume 4x normal" },
      { name: "correlation_break", active: true, strength: 0.78, detail: "Altcoins pumping, BTC stable" },
    ],
    timestamp: "2026-02-15T14:32:00Z",
    status: "active",
    outcome: null,
  },
  {
    id: "pred_002",
    type: "STOCK",
    asset: "NVDA",
    prediction: "EARNINGS_BEAT",
    confidence: 78,
    timeframe: "3 days",
    targetMove: "+8% to +15%",
    entryPrice: "$520",
    targetPrice: "$561 - $598",
    signals: [
      { name: "options_surge", active: true, strength: 0.85, detail: "15,000 call contracts (5x normal)" },
      { name: "insider_buying", active: true, strength: 0.80, detail: "3 execs bought $2M shares" },
      { name: "analyst_upgrade", active: true, strength: 0.75, detail: "MS raised target 20%" },
      { name: "supplier_signal", active: true, strength: 0.82, detail: "TSMC strong AI chip orders" },
      { name: "sentiment_shift", active: false, strength: 0.45, detail: "Media tone shifting" },
    ],
    timestamp: "2026-02-15T09:15:00Z",
    status: "active",
    outcome: null,
  },
  {
    id: "pred_003",
    type: "POLITICAL",
    asset: "Fed Rate Decision",
    prediction: "RATE_CUT",
    confidence: 81,
    timeframe: "30 days",
    targetMove: "-25 bps",
    entryPrice: null,
    targetPrice: null,
    signals: [
      { name: "cabinet_signals", active: true, strength: 0.88, detail: "Treasury Sec tone shift" },
      { name: "betting_markets", active: true, strength: 0.85, detail: "Polymarket 78% rate cut" },
      { name: "fed_speech", active: true, strength: 0.79, detail: "Dovish language detected" },
      { name: "economic_data", active: true, strength: 0.82, detail: "CPI trending down" },
      { name: "media_narrative", active: false, strength: 0.55, detail: "Mixed coverage" },
    ],
    timestamp: "2026-02-14T16:00:00Z",
    status: "active",
    outcome: null,
  },
  {
    id: "pred_004",
    type: "CRYPTO",
    asset: "ETH",
    prediction: "PUMP",
    confidence: 73,
    timeframe: "48-72 hours",
    targetMove: "+8% to +12%",
    entryPrice: "$3,200",
    targetPrice: "$3,456 - $3,584",
    signals: [
      { name: "whale_accumulation", active: true, strength: 0.75, detail: "Large wallets accumulating" },
      { name: "social_surge", active: true, strength: 0.70, detail: "Reddit activity up 200%" },
      { name: "exchange_outflow", active: true, strength: 0.72, detail: "ETH leaving exchanges" },
      { name: "volume_spike", active: true, strength: 0.68, detail: "Volume up 2.5x" },
      { name: "correlation_break", active: false, strength: 0.40, detail: "Following BTC closely" },
    ],
    timestamp: "2026-02-15T11:20:00Z",
    status: "active",
    outcome: null,
  },
  {
    id: "pred_005",
    type: "STARTUP",
    asset: "TechStartupXYZ",
    prediction: "SUCCESS",
    confidence: 72,
    timeframe: "12-24 months",
    targetMove: null,
    entryPrice: null,
    targetPrice: null,
    signals: [
      { name: "authentic_founder", active: true, strength: 0.80, detail: "Consistent messaging, strong vision" },
      { name: "strong_retention", active: true, strength: 0.78, detail: "4.2 Glassdoor, low turnover" },
      { name: "customer_traction", active: true, strength: 0.75, detail: "MRR growing 15% MoM" },
      { name: "funding_velocity", active: true, strength: 0.70, detail: "Series B in 18 months" },
      { name: "market_timing", active: false, strength: 0.50, detail: "Competitive market" },
    ],
    timestamp: "2026-02-13T08:00:00Z",
    status: "active",
    outcome: null,
  },
];

export const historicalPredictions = [
  { id: "h001", type: "CRYPTO", asset: "BTC", prediction: "PUMP", confidence: 82, outcome: "correct", date: "2026-01-28" },
  { id: "h002", type: "CRYPTO", asset: "ETH", prediction: "PUMP", confidence: 75, outcome: "correct", date: "2026-01-25" },
  { id: "h003", type: "STOCK", asset: "AAPL", prediction: "EARNINGS_BEAT", confidence: 71, outcome: "incorrect", date: "2026-01-22" },
  { id: "h004", type: "CRYPTO", asset: "SOL", prediction: "PUMP", confidence: 88, outcome: "correct", date: "2026-01-20" },
  { id: "h005", type: "POLITICAL", asset: "Senate Vote", prediction: "PASS", confidence: 79, outcome: "correct", date: "2026-01-18" },
  { id: "h006", type: "STOCK", asset: "TSLA", prediction: "BULLISH", confidence: 74, outcome: "correct", date: "2026-01-15" },
  { id: "h007", type: "STARTUP", asset: "AIStartup", prediction: "SUCCESS", confidence: 76, outcome: "correct", date: "2026-01-12" },
  { id: "h008", type: "CRYPTO", asset: "BTC", prediction: "DUMP", confidence: 70, outcome: "incorrect", date: "2026-01-10" },
  { id: "h009", type: "STOCK", asset: "NVDA", prediction: "EARNINGS_BEAT", confidence: 83, outcome: "correct", date: "2026-01-08" },
  { id: "h010", type: "CRYPTO", asset: "DOGE", prediction: "PUMP", confidence: 71, outcome: "correct", date: "2026-01-05" },
  { id: "h011", type: "POLITICAL", asset: "Policy Change", prediction: "APPROVED", confidence: 85, outcome: "correct", date: "2026-01-03" },
  { id: "h012", type: "STOCK", asset: "AMZN", prediction: "EARNINGS_BEAT", confidence: 77, outcome: "correct", date: "2025-12-28" },
  { id: "h013", type: "CRYPTO", asset: "BTC", prediction: "PUMP", confidence: 80, outcome: "correct", date: "2025-12-25" },
  { id: "h014", type: "STARTUP", asset: "FinTechCo", prediction: "FAILURE", confidence: 73, outcome: "correct", date: "2025-12-20" },
  { id: "h015", type: "STOCK", asset: "META", prediction: "BULLISH", confidence: 72, outcome: "incorrect", date: "2025-12-18" },
];

export const performanceData = {
  overall: { accuracy: 74, predictions: 156, correct: 115 },
  crypto: { accuracy: 76, predictions: 52, correct: 40 },
  stocks: { accuracy: 68, predictions: 41, correct: 28 },
  startups: { accuracy: 75, predictions: 20, correct: 15 },
  political: { accuracy: 82, predictions: 22, correct: 18 },
  casino: { accuracy: 71, predictions: 21, correct: 15 },
};

export const accuracyOverTime = [
  { date: "Week 1", overall: 65, crypto: 60, stocks: 55, political: 70 },
  { date: "Week 2", overall: 68, crypto: 65, stocks: 60, political: 72 },
  { date: "Week 3", overall: 70, crypto: 70, stocks: 62, political: 75 },
  { date: "Week 4", overall: 72, crypto: 73, stocks: 65, political: 78 },
  { date: "Week 5", overall: 71, crypto: 72, stocks: 64, political: 80 },
  { date: "Week 6", overall: 74, crypto: 76, stocks: 68, political: 82 },
  { date: "Week 7", overall: 73, crypto: 75, stocks: 67, political: 81 },
  { date: "Week 8", overall: 74, crypto: 76, stocks: 68, political: 82 },
];

export const recentAlerts = [
  { id: "a001", message: "BTC PUMP predicted - 87% confidence", type: "high", time: "2 hours ago", module: "CRYPTO" },
  { id: "a002", message: "NVDA earnings beat signal - 78% confidence", type: "medium", time: "5 hours ago", module: "STOCK" },
  { id: "a003", message: "Fed rate cut signals converging - 81%", type: "high", time: "1 day ago", module: "POLITICAL" },
  { id: "a004", message: "ETH accumulation pattern detected", type: "info", time: "1 day ago", module: "CRYPTO" },
  { id: "a005", message: "Unusual TSLA options activity", type: "medium", time: "2 days ago", module: "STOCK" },
];

export const paperTradingData = {
  startingCapital: 100000,
  currentValue: 118500,
  pnl: 18500,
  pnlPercent: 18.5,
  trades: 23,
  winRate: 74,
  bestTrade: { asset: "BTC", pnl: 8200, percent: 12.1 },
  worstTrade: { asset: "AAPL", pnl: -1800, percent: -3.2 },
  dailyPnl: [
    { date: "Feb 1", value: 100000 },
    { date: "Feb 3", value: 102300 },
    { date: "Feb 5", value: 105100 },
    { date: "Feb 7", value: 103800 },
    { date: "Feb 9", value: 108200 },
    { date: "Feb 11", value: 112500 },
    { date: "Feb 13", value: 115300 },
    { date: "Feb 15", value: 118500 },
  ],
};
